"""monitors and monitor events

Revision ID: 5910465f86f7
Revises: 0f32d70c2891
Create Date: 2026-09-28 16:04:17.488152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5910465f86f7'
down_revision: Union[str, Sequence[str], None] = '0f32d70c2891'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monitors',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('tenant_id', sa.String(length=26), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('interval_seconds', sa.Integer(), nullable=False),
    sa.Column('grace_seconds', sa.Integer(), server_default='0', nullable=False),
    sa.Column('renotify_seconds', sa.Integer(), nullable=True),
    sa.Column('channel_ids', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('title_template', sa.Text(), nullable=True),
    sa.Column('body_template', sa.Text(), nullable=True),
    sa.Column('state', sa.String(), server_default='pending', nullable=False),
    sa.Column('last_checkin_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_status', sa.String(), nullable=True),
    sa.Column('last_variables', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('last_alert_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("state IN ('pending', 'ok', 'missing')", name='ck_monitors_state'),
    sa.CheckConstraint('grace_seconds >= 0', name='ck_monitors_grace_non_negative'),
    sa.CheckConstraint('interval_seconds > 0', name='ck_monitors_interval_positive'),
    sa.CheckConstraint('renotify_seconds IS NULL OR renotify_seconds > 0', name='ck_monitors_renotify_positive'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_monitors_tenant_name')
    )
    op.create_index('ix_monitors_enabled', 'monitors', ['enabled'], unique=False)
    op.create_table('monitor_events',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('monitor_id', sa.String(length=26), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('dispatch_id', sa.String(), nullable=True),
    sa.CheckConstraint("kind IN ('imported', 'first_checkin', 'missing', 'recovered', 'alert', 'paused', 'resumed')", name='ck_monitor_events_kind'),
    sa.ForeignKeyConstraint(['monitor_id'], ['monitors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_monitor_events_monitor_at', 'monitor_events', ['monitor_id', 'at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_monitor_events_monitor_at', table_name='monitor_events')
    op.drop_table('monitor_events')
    op.drop_index('ix_monitors_enabled', table_name='monitors')
    op.drop_table('monitors')
    # ### end Alembic commands ###
